@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTA5MDg0NTEsImVtYWlsIjoiZGllZ29AaG90bS5jb20iLCJpYXQiOjE1OTA5MDgxNTF9.q4CwQmqu96PFJFoQuZHu3yyA_hvLLj1tQY7yR8CF2Ms

###
GET http://localhost:30003

###
GET http://localhost:30003/post
authorization: {{auth}}

###
POST http://localhost:30003/post
authorization: {{auth}}
Content-Type: application/json

{
    "post": "First Post"
}

###
DELETE http://localhost:30003/post/5ed1f118810be34e81bb7fde

//--------------------------------------------------------------------------------
###
POST http://localhost:30003/users
Content-Type: application/json

{
    "email": "diego@hotmail.com",
    "password": "diego1"
}

###
POST http://localhost:30003/users/login
Content-Type: application/json

{
    "email": "diego@hotm.com",
    "password": "diego1"
}