@auth = {{login.response.body.$.authorization}}
@port = 30003

###
GET http://localhost:{{port}}

###
GET http://localhost:{{port}}/post
authorization: {{auth}}

###
GET http://localhost:{{port}}/post?post=Lorem
authorization: {{auth}}

###
POST http://localhost:{{port}}/post?status=PU
authorization: {{auth}}
Content-Type: application/json

{
    "post": "First Post"
}

###
DELETE http://localhost:30003/post/5ed1f118810be34e81bb7fde

//--------------------------------------------------------------------------------
###
POST http://localhost:{{port}}/users
Content-Type: application/json

{
    "email": "diego@hotmail.com",
    "password": "diego1"
}

###
# @name login
POST http://localhost:{{port}}/users/login
Content-Type: application/json

{
    "email": "diego@hotmail.com",
    "password": "diego1"
}